<?php
/**
 * AUTO FIX .ENV - Chay file nay NGAY tren hosting
 * Script nay se TU DONG tao file .env voi API keys THAT
 */

$envFile = __DIR__ . '/.env';

echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Auto Fix .env</title>";
echo "<style>body{font-family:Arial;max-width:800px;margin:50px auto;padding:20px;background:#f5f5f5;}";
echo ".box{background:white;padding:20px;border-radius:8px;box-shadow:0 2px 10px rgba(0,0,0,0.1);margin:20px 0;}";
echo ".success{color:#28a745;font-size:20px;font-weight:bold;}";
echo ".error{color:#dc3545;font-size:18px;font-weight:bold;}";
echo ".code{background:#f8f9fa;padding:15px;border-left:4px solid #007bff;margin:10px 0;font-family:monospace;}";
echo ".btn{display:inline-block;padding:12px 24px;background:#007bff;color:white;text-decoration:none;border-radius:5px;margin:10px 5px;}";
echo ".btn:hover{background:#0056b3;}";
echo "h1{color:#333;border-bottom:3px solid #007bff;padding-bottom:10px;}";
echo "</style></head><body>";

echo "<h1>🔧 AUTO FIX .ENV FILE</h1>";

// QUAN TRONG: SAU KHI UPLOAD LEN HOSTING, MO FILE NAY VA THAY CAC PLACEHOLDER
// Uncomment va thay the bang API keys THAT cua ban:

$API_KEYS = [
    'GROQ_API_KEY' => 'YOUR_GROQ_API_KEY_HERE',  // Lay tai: https://console.groq.com/keys
    'CLIPDROP_API_KEY' => 'YOUR_CLIPDROP_API_KEY_HERE',  // Lay tai: https://clipdrop.co/apis
    'UNSPLASH_ACCESS_KEY' => 'YOUR_UNSPLASH_ACCESS_KEY_HERE',  // Lay tai: https://unsplash.com/oauth/applications
    'GEMINI_API_KEY' => '',
    'OPENAI_API_KEY' => '',
];

// HOAC uncomment dong duoi va paste keys truc tiep:
// $API_KEYS = [
//     'GROQ_API_KEY' => 'gsk_...',
//     'CLIPDROP_API_KEY' => '03ac237e...',
//     'UNSPLASH_ACCESS_KEY' => '0LZ4fpA...',
//     'GEMINI_API_KEY' => '',
//     'OPENAI_API_KEY' => '',
// ];

$envContent = "# AI API Keys - Auto generated by auto_fix_env.php
GROQ_API_KEY={$API_KEYS['GROQ_API_KEY']}
GEMINI_API_KEY={$API_KEYS['GEMINI_API_KEY']}
OPENAI_API_KEY={$API_KEYS['OPENAI_API_KEY']}
CLIPDROP_API_KEY={$API_KEYS['CLIPDROP_API_KEY']}
UNSPLASH_ACCESS_KEY={$API_KEYS['UNSPLASH_ACCESS_KEY']}

# AI Configuration
AI_PROVIDER=groq
IMAGE_PROVIDER=clipdrop

# Blog Settings
BLOG_DEFAULT_LENGTH=very-short
BLOG_TOTAL_HASHTAGS=5
";

echo "<div class='box'>";

// Kiem tra xem da cap nhat API keys chua
if ($API_KEYS['GROQ_API_KEY'] === 'YOUR_GROQ_API_KEY_HERE') {
    echo "<p class='error'>❌ LOI: BAN CHUA CAP NHAT API KEYS!</p>";
    echo "<p>Vui long:</p>";
    echo "<ol>";
    echo "<li>Mo file <code>auto_fix_env.php</code> tren hosting (qua cPanel File Manager)</li>";
    echo "<li>Tim dong <code>\$API_KEYS = [...</code></li>";
    echo "<li>Thay the cac <code>YOUR_XXX_API_KEY_HERE</code> bang API keys that</li>";
    echo "<li>Luu file va chay lai</li>";
    echo "</ol>";
    echo "<p><strong>Lay API keys tai:</strong></p>";
    echo "<ul>";
    echo "<li>Groq: <a href='https://console.groq.com/keys' target='_blank'>https://console.groq.com/keys</a></li>";
    echo "<li>Clipdrop: <a href='https://clipdrop.co/apis' target='_blank'>https://clipdrop.co/apis</a></li>";
    echo "<li>Unsplash: <a href='https://unsplash.com/oauth/applications' target='_blank'>https://unsplash.com/oauth/applications</a></li>";
    echo "</ul>";
    echo "</div></body></html>";
    exit;
}

// Tao hoac cap nhat file .env
if (file_put_contents($envFile, $envContent)) {
    echo "<p class='success'>✅ THANH CONG!</p>";
    echo "<p>File .env da duoc tao/cap nhat voi API keys!</p>";
    
    // Hien thi noi dung
    echo "<div class='code'>" . nl2br(htmlspecialchars($envContent)) . "</div>";
    
    // Kiem tra quyen file
    if (is_readable($envFile)) {
        echo "<p class='success'>✅ File .env co the doc duoc</p>";
        
        // Test load env
        require_once __DIR__ . '/includes/env_loader.php';
        
        $groqKey = env('GROQ_API_KEY', '');
        $clipdropKey = env('CLIPDROP_API_KEY', '');
        
        echo "<h2>📋 KIEM TRA API KEYS:</h2>";
        echo "<div class='code'>";
        echo "Groq Key: " . (!empty($groqKey) ? '✅ Co (' . substr($groqKey, 0, 10) . '...)' : '❌ Khong co') . "<br>";
        echo "Clipdrop Key: " . (!empty($clipdropKey) ? '✅ Co (' . substr($clipdropKey, 0, 10) . '...)' : '❌ Khong co') . "<br>";
        echo "AI Provider: " . env('AI_PROVIDER', 'not set') . "<br>";
        echo "Image Provider: " . env('IMAGE_PROVIDER', 'not set') . "<br>";
        echo "</div>";
        
        echo "<h2>🎉 HOAN TAT!</h2>";
        echo "<p>Ban co the:</p>";
        echo "<a href='blog_admin.php' class='btn'>📝 Tao bai viet AI</a>";
        echo "<a href='check_api_keys.php' class='btn'>🔍 Kiem tra chi tiet</a>";
        
        echo "<hr style='margin:30px 0;'>";
        echo "<h2 style='color:#dc3545;'>⚠️ BAO MAT:</h2>";
        echo "<p style='color:#dc3545;font-weight:bold;'>SAU KHI SU DUNG XONG, HAY XOA FILE auto_fix_env.php NAY!</p>";
        echo "<p>File nay chua API keys va khong nen de cong khai.</p>";
        
    } else {
        echo "<p class='error'>❌ Khong doc duoc file .env!</p>";
        echo "<p>Vui long kiem tra quyen file (chmod 644)</p>";
    }
    
} else {
    echo "<p class='error'>❌ THAT BAI!</p>";
    echo "<p>Khong the tao file .env. Nguyen nhan co the:</p>";
    echo "<ul>";
    echo "<li>Khong co quyen ghi file tren hosting</li>";
    echo "<li>Thu muc bi bao ve</li>";
    echo "</ul>";
    
    echo "<h2>🔧 GIAI PHAP THU CONG:</h2>";
    echo "<p>1. Tao file .env thu cong qua cPanel File Manager</p>";
    echo "<p>2. Copy noi dung sau vao file:</p>";
    echo "<div class='code'>" . nl2br(htmlspecialchars($envContent)) . "</div>";
}

echo "</div>";

echo "</body></html>";
?>

